name: Get AWS SSM Parameter

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      build_stage: "dev"
    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Reporting variables from AWS SSM
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: " 
            /my-app/dev/db-url = database_url,
            /my-app/dev/db-password = database_password"
          withDecryption: false

      # - uses: dkershner6/aws-ssm-getparameters-action@v1
      #   with:
      #     parameterPairs: "/region/primary = PRIMARY_AWS_REGION,
      #       /accountAlias = AWS_ACCOUNT_ALIAS"
      #     # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
      #     # No limit on number of parameters. You can put new lines and spaces in as desired, they get trimmed out.
      #     withDecryption: "true" # defaults to true
