name: Get AWS SSM Parameter

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      build_stage: "dev"
    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Reporting variables from AWS SSM
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: "
            /my-app/${{env.build_stage}}/db-url = database_url,
            /my-app/${{env.build_stage}}/db-password = database_password"
          withDecryption: false # defaults to true

      - name: "Build & Deploy"
        run: |
          echo "You will now have access to the database_url => ${{env.database_url}} and database_password => ${{env.database_password}} environment variables in all your subsequent build steps"