name: Get AWS SSM Secrect

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      build_stage: "dev"
    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secret Names by Prefix
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            test/secret*
          parse-json-secrets: true
          
      - name: "Build & Deploy"
        run: |
          echo "You will now have access to the TEST_SECRET_API_KEY environment variables in all your subsequent build steps"
